- src/web/components/PrintRecord/__tests__/PrintPage-full-render-test.js
- src/web/components/PrintRecord/__tests__/PrintPage-test.js
- src/web/forms/fields/Diagnoses/__mocks__/index.js
- src/web/forms/fields/MultiInput/__mocks__/index.js
- src/web/forms/fields/MultiInput/index.js
- src/web/forms/fields/SubformList/__mocks__/index.js
> Bug/fix print page import/541

- src/store/reducers/dform/initial/styles.json
> Add duration field (Pharping)

- src/store/reducers/dform/initial/styles.json
> Add suggested pathology fields for pharping/536

- src/store/reducers/dform/initial/styles.json
Please check my new branch. Added "" in 5 placeholders.
> Added quotation marks to placeholder sentences in Mental form

- src/store/reducers/dform/initial/styles.json
Please review form for Mental - life events fields.
> Changed 3 sentences in Mental - life events

- src/store/reducers/dform/initial/styles.json
Fixed English parts mostly in Mental form, and some in others as well. Please have a look.
> First commit - change various form fields English

- src/store/reducers/dform/initial/styles.json
Please review typo fix to labels on various forms.
> Fixing various typos in pharping forms

- src/web/forms/DynamicForm.js
- src/web/forms/fields/Block.js
Fix design of `DynamicForm` and `Block` components
> Fix dynamic form design bulma/495

- src/web/forms/fields/SubformList/index.js
add `autoAdd` prop to `<SubformList>` component
if `true`:
New line is automatically added.
if `false`:
"Add new item" button appears to add new item
> (refs #588) Add 'autoAdd' prop to SubformList

- src/store/reducers/dform/initial/styles.json
- src/web/components/PatientView/index.js
- src/web/components/PrintRecord/PrintPage.js
- Remove figures
- Lab exams similar to Pharing ver.
- SubformList with "Add" button
- Blood pressure field with alerts
- Shrinking textarea
> [WIP] Anc customization/561

- data/pharping-medicine-list-brandnames.json
- src/store/reducers/dform/initial/styles.js
Reverts asha-nepal/AshaFusionCross#621
> Revert "Add medicine brandnames list for pharping"

- src/web/components/PatientView/Footer.js
- src/web/components/PatientView/index.js
- src/web/sass/design.sass
Fix markups of `<Footer>` component to be compatible with bulma CSS framework.
> Refine Footer

- src/store/reducers/dform/initial/styles.json
The form fields which are irreverent to pharping hospital are removed.
> Removed unnecessary patient field codes

- src/store/reducers/dform/initial/styles.json
New Serological Tests form data are added.
> New Pathology fields are updated

- src/store/reducers/dform/initial/styles.json
Widel Test And Mantoux form fields are added.
> Widel Test and Mantoux form fields added

- src/web/components/PatientView/Header.js
- src/web/components/PatientView/PrintRecord/PrintPathologyForm.js
- src/web/components/PatientView/PrintRecord/Signature.js
- src/web/components/PatientView/PrintRecord/index.js
- src/web/sass/form.sass
- src/web/sass/print.sass
In response to Issue: #667 
Implemented: Items 1 & 2
Still pending: implement the inclusion only of necessary fields (target fields need to be decided)
> Fix print form to fit header, added signature line, made print drop-down menu look better

- src/store/reducers/dform/initial/styles.json
Added selectors to physician/pathology as in #659
> Select pathology

- src/store/reducers/dform/initial/styles.json
- src/web/components/PatientView/PrintRecord/PrintPathology.js
- src/web/sass/form.sass
- src/web/sass/print.sass
Added normal ranges as specified in #661 
1) Reflected in `normalRange` field in `styles.json`
2) Addition of placeholder field to PrintPathology form & print-rendered form
3) Addition of style for placeholder field
> Added normal ranges to print form

- src/web/components/PatientView/PrintRecord/PrintPathologyForm.js
Issue #695 bugfix
Added normalRange to printPathologyForm
> Bugfix for no normalRanges showing up on PrintPathologyForm

- src/web/components/PatientView/PrintRecord/PrintPathologyForm.js
From suggestions/comments on pullrequest #700
> Addressing slight refactoring changes from pullrequest 700.

- src/store/reducers/dform/initial/styles.json
Copy the patient form definition from Pharping version without gynaecology fields
> Change patient form
